name: PHP CS Fixer

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main 
      
jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.3"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.21.1
        with:
          php-version: ${{ matrix.php }}

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --config=/path/to/php-cs-fixer.dist.php
